# Generated by Django 3.0 on 2019-12-14 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_CSS_URL',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_keyword',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_primary_colour',
            field=models.CharField(default='#ffffff', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_secondary_colour',
            field=models.CharField(default='#ffffff', max_length=7),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=128)),
                ('content_name', models.CharField(max_length=128)),
                ('store_location', models.URLField(blank=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Customer')),
            ],
        ),
    ]
