# Generated by Django 3.0 on 2019-12-16 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20191214_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('bundle_id', models.AutoField(primary_key=True, serialize=False)),
                ('bundle_name', models.CharField(max_length=120)),
                ('bundle_description', models.CharField(max_length=256)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Customer')),
            ],
        ),
    ]
