# Generated by Django 3.0 on 2019-12-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_contentbundlelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentViewer',
            fields=[
                ('content_viewer_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_viewer_first_name', models.CharField(max_length=120)),
                ('content_viewer_last_name', models.CharField(max_length=120)),
                ('content_viewer_email', models.CharField(max_length=120)),
                ('content_viewer_key', models.CharField(max_length=256)),
            ],
        ),
    ]
