# Generated by Django 3.0 on 2019-12-16 20:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewerBundleLink',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('percent_progress', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('bundle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Bundle')),
                ('viewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.ContentViewer')),
            ],
        ),
    ]
